[features]
seeds = false
skip-lint = false
[programs.localnet]
phr_core = "GbcXdmj7dycduP6b7FBSq5x9bmDYBjPTbUzvVDrm4TxJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/kunalchhabra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
